TEMPLATE = app
CONFIG += console
CONFIG -= qt

INCLUDEPATH += \
    ../../library/cocos2dx/ \
    ../../library/cocos2dx/platform/ \
    ../../library/cocos2dx/platform/win32/ \
    ../../library/cocos2dx/platform/third_party/win32/OGLES/ \
    ../../library/cocos2dx/include/ \
    ../../library/extensions/ \
    ../../library/CocosDenshion/include/ \
    ../../library/cocos2dx/kazmath/include/ \
    ../../library/scripting/lua/cocos2dx_support/ \
    ../../library/scripting/lua/lua/ \
    ../../library/scripting/lua/tolua/ \
    ../../__graduation_project/Classes/JSON/include/\
    ../../__graduation_project/Classes/JSON/include/JsonBox/\

LIBS += \
    -LD:/Documents/GitHub/library/Debug.win32/ \
    -llibcocos2d \
    -llibcocosdenshion \
    -llibExtensions \
    -llibzlib \
    -lliblua \
    -lglew32 \
    -lliblua \
    -llibchipmunk \

DEFINES += WIN32 _WINDOWS

SOURCES += \
    main.cpp \
    ../Classes/JSON/src/Value.cpp \
    ../Classes/JSON/src/SolidusEscaper.cpp \
    ../Classes/JSON/src/Object.cpp \
    ../Classes/JSON/src/Indenter.cpp \
    ../Classes/JSON/src/IndentCanceller.cpp \
    ../Classes/JSON/src/Escaper.cpp \
    ../Classes/JSON/src/Convert.cpp \
    ../Classes/JSON/src/Array.cpp \
    ../Classes/MCTrigger.cpp \
    ../Classes/MCTestLua.cpp \
    ../Classes/MCTestController.cpp \
    ../Classes/MCTestbed.cpp \
    ../Classes/MCTaskStorage.cpp \
    ../Classes/MCTaskStatus.cpp \
    ../Classes/MCTaskManager.cpp \
    ../Classes/MCTaskContext.cpp \
    ../Classes/MCTaskAccessor.cpp \
    ../Classes/MCTask.cpp \
    ../Classes/MCStateLayer.cpp \
    ../Classes/MCSplashScene.cpp \
    ../Classes/MCScript.cpp \
    ../Classes/MCScenePackage.cpp \
    ../Classes/MCSceneManager.cpp \
    ../Classes/MCRoleEntity.cpp \
    ../Classes/MCRole.cpp \
    ../Classes/MCPointExtension.cpp \
    ../Classes/MCNPC.cpp \
    ../Classes/MCNormalBattleImpl.cpp \
    ../Classes/MCMutiplayerBattleImpl.cpp \
    ../Classes/MCMonster.cpp \
    ../Classes/MCMicsUtil.cpp \
    ../Classes/MCMainMenuScene.cpp \
    ../Classes/MCLuaCocos2d.cpp \
    ../Classes/MCJSONModifier.cpp \
    ../Classes/MCJoystick.cpp \
    ../Classes/MCJoypad.cpp \
    ../Classes/MCItem.cpp \
    ../Classes/MCHero.cpp \
    ../Classes/MCGeometry.cpp \
    ../Classes/MCGameState.cpp \
    ../Classes/MCGameScene.cpp \
    ../Classes/MCFaceBox.cpp \
    ../Classes/MCEffect.cpp \
    ../Classes/MCDungeonMaster.cpp \
    ../Classes/MCDice.cpp \
    ../Classes/MCDialogue.cpp \
    ../Classes/MCDialog.cpp \
    ../Classes/MCDetailScene.cpp \
    ../Classes/MCDetailLayer.cpp \
    ../Classes/MCControllerLayer.cpp \
    ../Classes/MCControllerDelegate.cpp \
    ../Classes/MCBattle.cpp \
    ../Classes/MCBase64.cpp \
    ../Classes/MCBarrier.cpp \
    ../Classes/AppDelegate.cpp \
    ../../library/scripting/lua/lua/print.c \
    ../../library/scripting/lua/lua/lzio.c \
    ../../library/scripting/lua/lua/lvm.c \
    ../../library/scripting/lua/lua/lundump.c \
    ../../library/scripting/lua/lua/lua.c \
    ../../library/scripting/lua/lua/ltm.c \
    ../../library/scripting/lua/lua/ltablib.c \
    ../../library/scripting/lua/lua/ltable.c \
    ../../library/scripting/lua/lua/lstrlib.c \
    ../../library/scripting/lua/lua/lstring.c \
    ../../library/scripting/lua/lua/lstate.c \
    ../../library/scripting/lua/lua/lparser.c \
    ../../library/scripting/lua/lua/loslib.c \
    ../../library/scripting/lua/lua/lopcodes.c \
    ../../library/scripting/lua/lua/lobject.c \
    ../../library/scripting/lua/lua/loadlib.c \
    ../../library/scripting/lua/lua/lmem.c \
    ../../library/scripting/lua/lua/lmathlib.c \
    ../../library/scripting/lua/lua/llex.c \
    ../../library/scripting/lua/lua/liolib.c \
    ../../library/scripting/lua/lua/linit.c \
    ../../library/scripting/lua/lua/lgc.c \
    ../../library/scripting/lua/lua/lfunc.c \
    ../../library/scripting/lua/lua/ldump.c \
    ../../library/scripting/lua/lua/ldo.c \
    ../../library/scripting/lua/lua/ldebug.c \
    ../../library/scripting/lua/lua/ldblib.c \
    ../../library/scripting/lua/lua/lcode.c \
    ../../library/scripting/lua/lua/lbaselib.c \
    ../../library/scripting/lua/lua/lauxlib.c \
    ../../library/scripting/lua/lua/lapi.c \
    ../../library/scripting/lua/tolua/tolua_to.c \
    ../../library/scripting/lua/tolua/tolua_push.c \
    ../../library/scripting/lua/tolua/tolua_map.c \
    ../../library/scripting/lua/tolua/tolua_is.c \
    ../../library/scripting/lua/tolua/tolua_event.c \
    ../../library/scripting/lua/cocos2dx_support/tolua_fix.c \
    ../../library/scripting/lua/cocos2dx_support/Cocos2dxLuaLoader.cpp \
    ../../library/scripting/lua/cocos2dx_support/tolua_fix.c \
    ../../library/scripting/lua/cocos2dx_support/Cocos2dxLuaLoader.cpp \
    ../../library/scripting/lua/cocos2dx_support/CCLuaEngine.cpp

HEADERS += \
    ../Classes/JSON/include/JsonBox.h \
    ../Classes/JSON/include/JsonBox/Value.h \
    ../Classes/JSON/include/JsonBox/SolidusEscaper.h \
    ../Classes/JSON/include/JsonBox/OutputFilter.h \
    ../Classes/JSON/include/JsonBox/Object.h \
    ../Classes/JSON/include/JsonBox/Indenter.h \
    ../Classes/JSON/include/JsonBox/IndentCanceller.h \
    ../Classes/JSON/include/JsonBox/Grammar.h \
    ../Classes/JSON/include/JsonBox/Escaper.h \
    ../Classes/JSON/include/JsonBox/Convert.h \
    ../Classes/JSON/include/JsonBox/Array.h \
    ../Classes/MCType.h \
    ../Classes/MCTrigger.h \
    ../Classes/MCTestLua.h \
    ../Classes/MCTestLayer.h \
    ../Classes/MCTestGame.h \
    ../Classes/MCTestController.h \
    ../Classes/MCTestbed.h \
    ../Classes/MCTaskStorage.h \
    ../Classes/MCTaskStatus.h \
    ../Classes/MCTaskManager.h \
    ../Classes/MCTaskContext.h \
    ../Classes/MCTaskAccessor.h \
    ../Classes/MCTask.h \
    ../Classes/MCStateLayer.h \
    ../Classes/MCSplashScene.h \
    ../Classes/MCScript.h \
    ../Classes/MCScenePackage.h \
    ../Classes/MCSceneManager.h \
    ../Classes/MCRoleProperty.h \
    ../Classes/MCRoleEntity.h \
    ../Classes/MCRole.h \
    ../Classes/MCPointExtension.h \
    ../Classes/MCObject.h \
    ../Classes/MCNPC.h \
    ../Classes/MCNormalBattleImpl.h \
    ../Classes/MCMutiplayerBattleImpl.h \
    ../Classes/MCMonster.h \
    ../Classes/MCMicsUtil.h \
    ../Classes/MCMainMenuScene.h \
    ../Classes/MCLuaCocos2d.h \
    ../Classes/MCJSONModifier.h \
    ../Classes/MCJoystick.h \
    ../Classes/MCJoypad.h \
    ../Classes/MCItem.h \
    ../Classes/MCHero.h \
    ../Classes/MCGeometry.h \
    ../Classes/MCGameState.h \
    ../Classes/MCGameScene.h \
    ../Classes/MCFaceBox.h \
    ../Classes/MCEffect.h \
    ../Classes/MCDungeonMaster.h \
    ../Classes/MCDice.h \
    ../Classes/MCDialogue.h \
    ../Classes/MCDialog.h \
    ../Classes/MCDetailScene.h \
    ../Classes/MCDetailLayer.h \
    ../Classes/MCControllerLayer.h \
    ../Classes/MCControllerDelegate.h \
    ../Classes/MCBattle.h \
    ../Classes/MCBase64.h \
    ../Classes/MCBarrier.h \
    ../Classes/AppMacros.h \
    ../Classes/AppDelegate.h \
    ../Classes/_T_.h \
    ../../library/scripting/lua/lua/lzio.h \
    ../../library/scripting/lua/lua/lvm.h \
    ../../library/scripting/lua/lua/lundump.h \
    ../../library/scripting/lua/lua/lualib.h \
    ../../library/scripting/lua/lua/luaconf.h \
    ../../library/scripting/lua/lua/lua.h \
    ../../library/scripting/lua/lua/ltm.h \
    ../../library/scripting/lua/lua/ltable.h \
    ../../library/scripting/lua/lua/lstring.h \
    ../../library/scripting/lua/lua/lstate.h \
    ../../library/scripting/lua/lua/lparser.h \
    ../../library/scripting/lua/lua/lopcodes.h \
    ../../library/scripting/lua/lua/lobject.h \
    ../../library/scripting/lua/lua/lmem.h \
    ../../library/scripting/lua/lua/llimits.h \
    ../../library/scripting/lua/lua/llex.h \
    ../../library/scripting/lua/lua/lgc.h \
    ../../library/scripting/lua/lua/lfunc.h \
    ../../library/scripting/lua/lua/ldo.h \
    ../../library/scripting/lua/lua/ldebug.h \
    ../../library/scripting/lua/lua/lcode.h \
    ../../library/scripting/lua/lua/lauxlib.h \
    ../../library/scripting/lua/lua/lapi.h \
    ../../library/scripting/lua/tolua/tolua++.h \
    ../../library/scripting/lua/tolua/tolua_event.h \
    ../../library/scripting/lua/cocos2dx_support/tolua_fix.h \
    ../../library/scripting/lua/cocos2dx_support/LuaCocos2d.h \
    ../../library/scripting/lua/cocos2dx_support/Cocos2dxLuaLoader.h \
    ../../library/scripting/lua/cocos2dx_support/CCLuaEngine.h \
    ../../library/scripting/lua/cocos2dx_support/tolua_fix.h \
    ../../library/scripting/lua/cocos2dx_support/LuaCocos2d.h \
    ../../library/scripting/lua/cocos2dx_support/Cocos2dxLuaLoader.h \
    ../../library/scripting/lua/cocos2dx_support/CCLuaEngine.h
